### ISSUE TITLE
Improve Lookup Server

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/lookup-server#82]
- [ ] [lookup-server/72](https://github.com/nextcloud/lookup-server/issues/72): Wrong return code when $signatureHandler->verify returns false
- [ ] [lookup-server/73](https://github.com/nextcloud/lookup-server/issues/73): Enhance the user handling logic to accept unsigned user upsert/delete operations for troubleshooting and testing
- [ ] [lookup-server/74](https://github.com/nextcloud/lookup-server/issues/74): Fully document the API
- [ ] [lookup-server/77](https://github.com/nextcloud/lookup-server/issues/77): Logging does not work (this has also been recently noticed by Renater see [#9625578](https://support.nextcloud.com/#ticket/zoom/25682))
- [ ] [lookup-server/78](https://github.com/nextcloud/lookup-server/issues/78): Reject duplicate users in a Global Scale deployment
- [ ] [lookup-server/79](https://github.com/nextcloud/lookup-server/issues/79): Why deleting a user does not delete the user entry in the users table?
- [ ] [lookup-server/pull-request/71](https://github.com/nextcloud/lookup-server/pull/71):Update version.php
